accept AbstractString for BigFloat construction (#28169)
This is a minor change to allow `BigFloat` construction from `AbstractString`. E.g.:

```
julia> BigFloat(strip(" 42"))
4.2e+01
```

Without this:

```
julia> BigFloat(strip(" 42"))
ERROR: MethodError: Cannot `convert` an object of type SubString{String} to an object of type BigFloat
...
```