Restrict vector arg eltype of read/copyuntil to UInt8
The previous implementation of `copyuntil` did not document what the vector
delimiter could be, but the implementation allowed it to be a vector of anything.
This laxness has the following problems:

1. It's semantically dubious to read until the first T in an IO, when IOs are
   generally conceptualized to contain bytes, and not Ts. This seems to suggest
   a notion of an IO "containing" T's, which is different from being able to
   read T's from the IO, and probably implies `x::T in io::IO` should also work.

3. The implementation is buggy, or at least has highly surprising consequences.
   For example:

```julia
julia> println(readuntil(IOBuffer("\1\2\3\4"), 0x0302))
UInt16[0x0201, 0x0403]

julia> println(readuntil(IOBuffer("\1\2\3\4\5"), 0x0302))
ERROR: EOFError: read end of file
```

2. The generic implementation is highly inefficient because it depends on
   `readeach`. It's difficult to make this generically efficient for arbitrary T.