Check `done` before `next` in the fallback `first`
The fallback `first` method for Any types wasn't checking the done status between `start` and `next`.  This simple patch simply adds a check and error message that is a bit more sensible than current errors.

Currently:

```julia
julia> first(Dict())
ERROR: BoundsError: attempt to access 16-element Array{Any,1}:
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
  at index [17]
 in first at abstractarray.jl:27
```

With this patch:

```julia
julia> first(Dict())
ERROR: collection is empty
 in first at abstractarray.jl:27
```

(I don't think there's a better error type to throw here as it will depend on the type if it's a BoundsError or KeyError or such. Cc @jakebolewski since you've been doing some error message cleanups along these lines.)