Clear warning about redefinition of macro
`FORCE_INLINE` is also defined in `src/support/dtypes.h`, and both `dtypes.h`
and `MurmurHash3.c` are included by `src/support/hashing.c`, causing a clash:

```
In file included from /home/mose/repo/julia/src/support/hashing.c:51:
/home/mose/repo/julia/src/support/MurmurHash3.c:15: warning: "FORCE_INLINE" redefined
   15 | #define FORCE_INLINE inline __attribute__((always_inline))
      |
In file included from /home/mose/repo/julia/src/support/hashing.c:7:
/home/mose/repo/julia/src/support/dtypes.h:120: note: this is the location of the previous definition
  120 | #define FORCE_INLINE static inline __attribute__((always_inline))
      |
```