Attempt to fix osx travis (#18563)
* Attempt to fix osx travis

We're now getting
> Error: You must `brew link autoconf` before staticfloat/julia/julia can be installed

Probably because Homebrew officially started supporting 10.12 Sierra, and that broke something.
Try to use the 10.10 Travis OSX image instead of the default 10.9 (https://docs.travis-ci.com/user/osx-ci-environment/)

* explicitly install cmake on osx travis

(cherry picked from commit 45bc17d41b40f271dd5ebb2357e7f3564f969007)