Call all-underscore identifiers write-only (#50830)
Followup to #45964, #46506, and
https://discourse.julialang.org/t/class-of-variables/83892.

The error
```
julia> println(_)
ERROR: syntax: all-underscore identifier used as rvalue
```
is hard to interpret if you are not familiar with the term `rvalue`,
which is not used in any other context in Julia, and as discussed
previously the use here is not clearly matching the wikipedia page
referred to in the documentation either.

This PR does away with the term `rvalue` by changing the error to
```
ERROR: syntax: all-underscore identifiers are write-only and their values cannot be used in expressions
```
and updates the documentation accordingly.