test-codegen: make jl_dump_compiles test more reliable (#23486)
This was a flaky test, and it's not entirely clear what it was testing.

Common failure was:
        FAILURE
    Error in testset codegen:
    Test Failed
      Expression: tempty == true
       Evaluated: false == true
    ERROR: LoadError: Test run finished with errors
    while loading C:\projects\julia\julia-a661736be5\share\julia\test\runtests.jl, in expression starting on line 29
    Command exited with code 1

(cherry picked from commit 46bff1bf83f82107369b23c3163a53aed4f9801c)