Trying to fix spawn-interpolation for macrocalls
Expand macrocalls when parsing async early, before recursing to
interpolate `$` variables. This fixes inner macrocalls that themselves
operate on `$`, by giving them the chance to use up the `$` _if they
use them_, before allowing `@async` / `@spawn` to do the intepolation
themselves.

But this still doesn't seem to be working correctly, since "outer
macrocalls" still aren't working, e.g.:
```julia
julia> @eval fetch(@async 2+$$x)
ERROR: syntax: "$" expression outside quote
```