Deprecate vectorize_1arg for Dates within module
Otherwise there are issues with functions being independently defined
within multiple modules:

```julia
julia> using Base.Dates

julia> unix2datetime(0)
WARNING: both Dates and Base export "unix2datetime"; uses of it in module Main must be qualified
ERROR: UndefVarError: unix2datetime not defined
```