Limit REPL suggestions to modules from which name is exported/public (#52418)
Close #52387 by implementing the suggestion in
https://github.com/JuliaLang/julia/issues/52387#issuecomment-1839152721.
After this, in a fresh session
```julia
julia> Diagonal
ERROR: UndefVarError: `Diagonal` not defined in `Main`
Suggestion: check for spelling errors or missing imports.
Hint: a global variable of this name also exists in LinearAlgebra.
```