slightly more actionable subtype declaration errors (#61635)
with embarrassing frequency do I write something like `struct Foo <:
AbstractArray end` and then get annoyed at how vague the error message
is. and I imagine as a new user this experience would be worse, since
the phrase `data type` doesn't mean much and it's not obvious why we
can't do this

this PR tries to make the error message slightly more evocative of what
the remedy should be to the subtype declaration, and adds a few more
specific messages for some cases (some more niche than others)

```
struct Foo <: AbstractArray end
ERROR: invalid subtyping in definition of Foo: can only subtype data types. # before
ERROR: invalid subtyping in definition of Foo: supertype `AbstractArray{T, N}` has unbound type parameters. # after

struct Foo <: Union{Int, Float64} end
ERROR: invalid subtyping in definition of Foo: can only subtype data types. # before
ERROR: invalid subtyping in definition of Foo: cannot subtype a Union type. # after

(struct Foo <: T end) where T
ERROR: invalid subtyping in definition of Foo: can only subtype data types. # before
ERROR: invalid subtyping in definition of Foo: cannot subtype a type variable. # after

struct Foo <: 1 end
ERROR: invalid subtyping in definition of Foo: can only subtype data types. # before
ERROR: invalid subtyping in definition of Foo: supertype must be a type, got a value of type `Int64`. # after
```