small typo in code example in the llvm.md documentation (#49943)
The code in the documentation returns an error:
```
ERROR: MethodError: no method matching _dump_function(::typeof(+), ::Type{Tuple{Int64, Int64}}, ::Bool, ::Bool, ::Bool, ::Bool, ::Symbol, ::Bool, ::Symbol)
```
apparently, one boolean variable was missing from the call to
`InteractiveUtils._dump_function`. Adding one `false` at the end of the
call should fix that.