Remove Base.Parallel export.
It appears `Base.Parallel` has been renamed to `Base.Distributed`, but is
still exported.  Thus, the export in base/exports.jl is not valid anymore.  In
particular, when doing e.g. a `[ s for s in names(Base) if
typeof(getfield(Base,s))<:Function]` an UnDefVar error is thrown on 'Parallel'.

```jl
julia> [ s for s in names(Base) if typeof(getfield(Base,s))<:Function]
ERROR: UndefVarError: Parallel not defined
Stacktrace:
 [1] advance_filter(::##6#8, ::Array{Symbol,1}, ::Tuple{Bool,Symbol,Int64}) at ./iterators.jl:270
 [2] next at ./generator.jl:44 [inlined]
 [3] grow_to!(::Array{Symbol,1}, ::Base.Generator{Base.Iterators.Filter{##6#8,Array{Symbol,1}},##5#7}, ::Tuple{Bool,Symbol,Int64}) at ./array.jl:475
 [4] grow_to!(::Array{Union{},1}, ::Base.Generator{Base.Iterators.Filter{##6#8,Array{Symbol,1}},##5#7}, ::Tuple{Bool,Symbol,Int64}) at ./array.jl:483
 [5] grow_to!(::Array{Symbol,1}, ::Base.Generator{Base.Iterators.Filter{##6#8,Array{Symbol,1}},##5#7}) at ./array.jl:468
 [6] collect(::Base.Generator{Base.Iterators.Filter{##6#8,Array{Symbol,1}},##5#7}) at ./array.jl:412
```