Print warning to STDERR instead of throwing exception
Since throwing an exception would allocate, which is illegal from the
`jl_static_*` function(s).

```
julia> ccall(:jl_static_show, Cvoid, (Ptr{Cvoid}, Any), p.in, x)
ERROR: static_show: Exit after 10,000 iterations of supertype(). Presuming invalid cycle in datatype object.
```