Update macros.jl
Changes `splitrange` to use `Integer` instead of `Int` so that mixed-width ints can be used. This fixes the following LightGraphs issue on 32-bit machines:
```
julia> g = Graph(10,20)
{10, 20} undirected simple Int32 graph

julia> Parallel.stress_centrality(g);

julia> g = Graph{Int64}(g)
{10, 20} undirected simple Int64 graph

julia> Parallel.stress_centrality(g);
ERROR: MethodError: no method matching splitrange(::Int64, ::Int32)
Closest candidates are:
  splitrange(::Int32, ::Int32) at /buildworker/worker/package_linuxarmv7l/build/usr/share/julia/stdlib/v1.0/Distributed/src/macros.jl:235
```