Fix casts and DLLEXPORTs for MSVC build of threading code
Use gcc __thread when building with gcc on windows

DLLEXPORT JL_THREAD except on MSVC

should help with:

d:\code\msys64\home\tony\julia\src\julia.h(591) : error C2492: 'jl_pgcstack' : '
thread' data may not have dll interface
d:\code\msys64\home\tony\julia\src\julia.h(1485) : error C2492: 'jl_current_task
' : 'thread' data may not have dll interface
d:\code\msys64\home\tony\julia\src\julia.h(1486) : error C2492: 'jl_root_task' :
 'thread' data may not have dll interface
d:\code\msys64\home\tony\julia\src\julia.h(1487) : error C2492: 'jl_exception_in
_transit' : 'thread' data may not have dll interface
d:\code\msys64\home\tony\julia\src\julia.h(1488) : error C2492: 'jl_task_arg_in_
transit' : 'thread' data may not have dll interface
d:/code/msys64/home/Tony/julia/src/jltypes.c(1910) : error C2664: 'LONG64 _Inter
lockedCompareExchange64(volatile LONG64 *,LONG64,LONG64)' : cannot convert argum
ent 1 from 'volatile uint64_t *' to 'volatile LONG64 *'
        Types pointed to are unrelated; conversion requires reinterpret_cast, C-
style cast or function-style cast
d:/code/msys64/home/Tony/julia/src/jltypes.c(1913) : error C2664: 'LONG64 _Inter
lockedCompareExchange64(volatile LONG64 *,LONG64,LONG64)' : cannot convert argum
ent 1 from 'volatile uint64_t *' to 'volatile LONG64 *'
        Types pointed to are unrelated; conversion requires reinterpret_cast, C-
style cast or function-style cast
d:/code/msys64/home/Tony/julia/src/jltypes.c(1993) : error C2664: 'LONG64 _Inter
lockedCompareExchange64(volatile LONG64 *,LONG64,LONG64)' : cannot convert argum
ent 1 from 'volatile uint64_t *' to 'volatile LONG64 *'
        Types pointed to are unrelated; conversion requires reinterpret_cast, C-
style cast or function-style cast
d:/code/msys64/home/Tony/julia/src/jltypes.c(2000) : error C2664: 'LONG64 _Inter
lockedCompareExchange64(volatile LONG64 *,LONG64,LONG64)' : cannot convert argum
ent 1 from 'volatile uint64_t *' to 'volatile LONG64 *'
        Types pointed to are unrelated; conversion requires reinterpret_cast, C-
style cast or function-style cast