Fix `BoundsError` in `Printf.Format`
For invalid format strings, an access in `Printf.Format` could be out of bounds. You can see the problem with (needs --check-bounds=no)
```
julia> using Printf

julia> secret = "Qu1et"
"Qu1et"

julia> Printf.Format(SubString("%1" * secret, 1:2))
ERROR: InvalidFormatStringError: 'Q' is not a valid type specifier
```

where part of the secret (the 'Q') is revealed. This example is of course not critical at all, but it shows that memory after the provided memory range (two code units) is accessed (code unit 3) and revealed. `Printf.Format` is accepting an `AbstractString` which, according to `codeunits`' docstring, can have arbitrary width enabling the caller theoretically to reveal an arbitrary amount of memory. I wouldn't know that anyone uses such types, so this should typically be limited to up to four bytes.