Give suggestions for vector->row vector confusion
Some new users might get confused when they create a vector without
commas, and end up with a matrix that does not match the methods he
tries to use. After this patch the error will contain a suggestion.

```julia
julia> a = [1 2 3]
1x3 Array{Int64,2}:
 1  2  3

julia> sort(a)
ERROR: `sort` has no method matching sort(::Array{Int64,2})

You might have used a 2d row vector where a 1d column vector was required.
Note the difference between 1d column vector [1,2,3] and 2d row vector [1 2 3]
You can convert to a column vector with the vec() function
```