InteractiveUtils: support syntax found in stacktraces for introspection macros (#58222)
Continuing the work done at #57909, this PR adds support for the
following syntax:
```julia
@code_typed f(some_undef_var::Int) # some_undef_var is ignored, only the annotation is used
@code_typed f(; x::Int) # same here, the name is used but not the value
```
This should allow us to copy and paste signatures found in stacktraces,
such as
```julia
julia> f(x; y = 3) = error()
f (generic function with 1 method)

julia> f(1)
ERROR: 
Stacktrace:
 [1] error()
   @ Base ./error.jl:45
 [2] f(x::Int64; y::Int64)
   @ Main ./REPL[40]:1
 [3] top-level scope
   @ REPL[41]:1
   
julia> asin(-2)
ERROR: DomainError with -2.0:
asin(x) is not defined for |x| > 1.
Stacktrace:
 [1] asin_domain_error(x::Float64)
   @ Base.Math ./special/trig.jl:429
 [2] asin(x::Float64)
   @ Base.Math ./special/trig.jl:443
```

where any function call may be copied and pasted into `@code_typed`,
`@edit` etc as is, provided that the function and argument types are
defined in the active module (i.e. `Main`).

Thanks @topolarity for the idea.

---------

Co-authored-by: Cédric Belmant <cedric.belmant@juliahub.com>