Resolve all method ambiguities in LinearAlgebra (#28749)
* Add a test to check method ambiguities

* Use StridedMatrix to avoid method ambiguity; fixes #27405

* Avoid method ambiguity in promote_leaf_eltypes

This change is only for making Test.detect_ambiguities and shouldn't
introduce any change in working code (unless it depends on MethodError).

Before this change, we have:

julia> LinearAlgebra.promote_leaf_eltypes(())
ERROR: MethodError: LinearAlgebra.promote_leaf_eltypes(::Tuple{}) is ambiguous. Candidates:

With this change, we have:

julia> LinearAlgebra.promote_leaf_eltypes(())
Bool