Update modules.rst adding type to show for v0.5 (#18018)
Update to add type annotation otherwise we get
```
ERROR: MethodError: no method matching display(::MyType)
```
(cherry picked from commit 5076870387429448cddc8850aea442218b8d670d)