Revert "fix codegen side of `sizeof` for SimpleVector"
This reverts commit 931cdbe8ef4eb24c79344b93e4a759f8a651e40a.

This commit broke tests on OS X:

ERROR: LoadError: On worker 7:
LoadError("/Users/stefan/projects/julia.alt/test/abstractarray.jl",469,ErrorException("test failed: 8 == 32\n in expression: Base.elsize(B) == sizeof(T.parameters)"))
 in default_handler at test.jl:28
 in do_test at test.jl:53
 in test_primitives at /Users/stefan/projects/julia.alt/test/abstractarray.jl:207
 in anonymous at no file:472
 in include_string at loading.jl:233
 in include_from_node1 at ./loading.jl:274
 in runtests at /Users/stefan/projects/julia.alt/test/testdefs.jl:179
 in anonymous at multi.jl:889
 in run_work_thunk at multi.jl:642
 in anonymous at task.jl:889