don't throw EOFError from sleep
We will no longer throw a error if the timer fires after we first checked set.

But still keeps this case functional:
```
julia> t = Timer(1000000000);

julia> close(t)

julia> t.set
false

julia> wait(t)
ERROR: EOFError: read end of file
Stacktrace:
 [1] wait(t::Timer)
   @ Base .\asyncevent.jl:159
 [2] top-level scope
   @ REPL[16]:1
```