Improve `MethodError` message for anonymous functions (#57340)
If a MethodError arises on a anonyomous function, the words "anonymous
function" are printed in the error like so:
```julia
g=(x,y)->x+y
g(1,2,3)
```
```
ERROR: MethodError: no method of the anonymous function var"#5#6" matching (::var"#5#6")(::Int64, ::Int64, ::Int64)
The function `#5` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  (::var"#5#6")(::Any, ::Any)
   @ Main REPL[4]:1
```

See the [original pull
request](https://github.com/JuliaLang/julia/pull/57319) and
[issue](https://github.com/JuliaLang/julia/issues/56325) #56325