remove type piracy from `==` defined in `Compiler` (#56541)
`Compiler.:(==)` is now identical to `Base.:(==)`, so the following `==`
methods defined in typelattice.jl are considered type piracy:
https://github.com/JuliaLang/julia/blob/1edc6f1b7752ed67059020ba7ce174dffa225954/Compiler/src/typelattice.jl#L194-L197

In fact, loading `Compiler` as a standard library with this code can
sometimes result in errors like the following:
```julia
julia> using Compiler

julia> Int == Core.Const(1)
ERROR: MethodError: ==(::Type{Int64}, ::Core.Const) is ambiguous.
...
```

Since these `==` definitions no longer seem necessary, this commit
simply removes them to resolve the issue.

@nanosoldier `runbenchmarks("inference", vs=":master")`