Revert "Remove world-age freezing when calling generator"
This reverts commit 4df638db6e37b90364ada09f2cdd734dab8f3b5b.

It caused a weird error during julia's precompilation:
```
Generating precompile statements...┌ Error: Failed to precompile precompile(Tuple{getfield(Dates, Symbol("##s624#32")), Type{Tuple{Dates.DatePart{Char(0x59000000)}, Dates.Delim{Char, 1}, Dates.DatePart{Char(0x6d000000)}, Dates.Delim{Char, 1}, Dates.DatePart{Char(0x64000000)}, Dates.Delim{Char, 1}, Dates.DatePart{Char(0x48000000)}, Dates.Delim{Char, 1}, Dates.DatePart{Char(0x4d000000)}, Dates.Delim{Char, 1}, Dates.DatePart{Char(0x53000000)}, Dates.Delim{Char, 1}, Dates.DatePart{Char(0x73000000)}}}, Type{typeof(Dates.format)}, Type{Base.GenericIOBuffer{Array{UInt8, 1}}}, Type{Dates.DateTime}, Type{Dates.DateFormat{Symbol("YYYY-mm-dd\THH:MM:SS.s"), Tuple{Dates.DatePart{Char(0x59000000)}, Dates.Delim{Char, 1}, Dates.DatePart{Char(0x6d000000)}, Dates.Delim{Char, 1}, Dates.DatePart{Char(0x64000000)}, Dates.Delim{Char, 1}, Dates.DatePart{Char(0x48000000)}, Dates.Delim{Char, 1}, Dates.DatePart{Char(0x4d000000)}, Dates.Delim{Char,
1}, Dates.DatePart{Char(0x53000000)}, Dates.Delim{Char, 1}, Dates.DatePart{Char(0x73000000)}}}}})
└ @ Main.anonymous /Users/nathan.daly/src/julia2/contrib/generate_precompile.jl:167
ERROR: LoadError: LoadError: syntax: invalid escape sequence
```

Also, I'm not 100% sure _what_ the right world-age should be to run
these functions in. I _think_ it makes sense to just use the current
world-age, like a regular function, but it could also be reasonable to
run them always at the latest world age (which is close to what we're
currently doing) since they're currently run as pure functions.

But if we run them at the latest world-age, will this behave weirdly?:
```julia
julia> @generated foo(x) = baz(x)
foo (generic function with 1 method)

julia> baz(x) = 1
baz (generic function with 1 method)

julia> function f()
           @eval baz(x) = 2
           foo(1)
       end
f (generic function with 1 method)

julia> f()  # Should be 1, but if `foo()` is always run at latest world-age, will this be 2? Maybe this would work just-fine, actually?
```