Fix JL_ATOMIC_COMPARE_AND_SWAP under MSVC
fixes
d:/code/msys64/home/Tony/julia/src/jltypes.c(1910) : error C2664: 'LONG64 _Inter
lockedCompareExchange64(volatile LONG64 *,LONG64,LONG64)' : cannot convert argum
ent 1 from 'volatile uint64_t *' to 'volatile LONG64 *'
        Types pointed to are unrelated; conversion requires reinterpret_cast, C-
style cast or function-style cast
d:/code/msys64/home/Tony/julia/src/jltypes.c(1913) : error C2664: 'LONG64 _Inter
lockedCompareExchange64(volatile LONG64 *,LONG64,LONG64)' : cannot convert argum
ent 1 from 'volatile uint64_t *' to 'volatile LONG64 *'
        Types pointed to are unrelated; conversion requires reinterpret_cast, C-
style cast or function-style cast
d:/code/msys64/home/Tony/julia/src/jltypes.c(1993) : error C2664: 'LONG64 _Inter
lockedCompareExchange64(volatile LONG64 *,LONG64,LONG64)' : cannot convert argum
ent 1 from 'volatile uint64_t *' to 'volatile LONG64 *'
        Types pointed to are unrelated; conversion requires reinterpret_cast, C-
style cast or function-style cast
d:/code/msys64/home/Tony/julia/src/jltypes.c(2000) : error C2664: 'LONG64 _Inter
lockedCompareExchange64(volatile LONG64 *,LONG64,LONG64)' : cannot convert argum
ent 1 from 'volatile uint64_t *' to 'volatile LONG64 *'
        Types pointed to are unrelated; conversion requires reinterpret_cast, C-
style cast or function-style cast

also define sleep for MSVC
Kernel32 Sleep takes milliseconds, ref https://msdn.microsoft.com/en-us/library/windows/desktop/ms686298(v=vs.85).aspx

fixes
d:/code/msys64/home/Tony/julia/src/threading.c(212) : error C3861: 'sleep': iden
tifier not found
d:/code/msys64/home/Tony/julia/src/threading.c(290) : error C3861: 'sleep': iden
tifier not found