Add builtin function name to add methods error (#59112)
```
julia> Base.throw(x::Int) = 1
ERROR: cannot add methods to builtin function `throw`
Stacktrace:
 [1] top-level scope
   @ REPL[1]:1
```

(cherry picked from commit 57def4d19ef79794439ef839e5e3b551323f49a2)