Adjust claims about the power of `parse(Complex...)`
The statement
> `parse(Complex{T}, string)` can parse complex numbers in common formats
is a bit exaggerating. Arguably one of the more common complex number output formats is that used by Fortran, which is of the form "(real, imag)". The current implementation of `parse` fails to parse this:
```
julia> parse(Complex{Float64}, "(1.0, 2.0)")
ERROR: ArgumentError: cannot parse "(1.0, 2.0)" as Float64
```