Pkg.submit has been moved to PkgDev in latest
I get the following error
```
julia> Pkg.submit("Images")
ERROR: Pkg.submit(pkg[, commit]) has been moved to the package PkgDev.jl.
Run Pkg.add("PkgDev") to install PkgDev on Julia v0.5-
 in submit(::ASCIIString) at ./pkg.jl:262
 in eval(::Module, ::Any) at ./boot.jl:267
```