Lower `const x = ...` to new builtin `Core.setconst!` (#58187)
Adds a new builtin, `Core.setconst!`, with the following signature:

```
    setconst!(module::Module, name::Symbol, [x])
```

The lowered `Expr(:const, :name, value)` form has been removed, saving
some
duplicated effort in the interpreter and code generation. `Expr(:const,
...)` is
now always lowered to the builtin.

```
julia> Meta.@lower const example = 123
:($(Expr(:thunk, CodeInfo(
1 ─ %1 = 123
│          builtin Core.setconst!(Main, :example, %1)
│        $(Expr(:latestworld))
└──      return %1
))))
```

The single-argument form of const, having no surface syntax, was
previously only
available through `eval(Expr(:const, :foo))`:

```
julia> eval(Expr(:const, :example))

julia> GlobalRef(Main, :example).binding
Binding Main.example
   38582:∞ - undefined const binding
   38579:38581 - undefined binding - guard entry
```

It survived lowering by being special-cased in `expand-toplevel-expr--`,
resulting in some inconsistencies:

```
julia> eval(:(begin $(Expr(:const, :example)) end))
ERROR: syntax: malformed expression
Stacktrace:
 [1] top-level scope
   @ none:1
 [2] eval(m::Module, e::Any)
   @ Core ./boot.jl:489
 [3] top-level scope
   @ REPL[1]:1
```

These are fixed now that const is always lowered.

---------

Co-authored-by: Jameson Nash <vtjnash@gmail.com>