`StepRange` constructor with an `OrdinalRange` argument (#57718)
The `StepRange` constructor currently doesn't convert from a
`StepRange`, but similar calls work with other range types such as
`StepRangeLen` and `UnitRange`.
```julia
julia> StepRange(2:1:4)
ERROR: MethodError: no method matching StepRange(::StepRange{Int64, Int64})
The type `StepRange` exists, but no method is defined for this combination of argument types when trying to construct it.
```
After this PR, it works:
```julia
julia> StepRange(2:1:4)
2:1:4
```