lowering: Allow chaining of `>:` in `where` (#57554)
This change removes an inconsistency between `>:` and `<:`. We were
parsing `where {A>:B>:C}` forms, but not recognizing them in lowering.

Before:
```
julia> Vector{T} where Int<:T<:Number
Vector{T} where Int64<:T<:Number

julia> Vector{T} where Number>:T>:Int
ERROR: syntax: invalid bounds in "where" around REPL[14]:1
```

After:
```
julia> Vector{T} where Number>:T>:Int
Vector{T} where Int64<:T<:Number
```

(cherry picked from commit 2e57730aa253b4d8dc90be56a4282bbece045ccc)