Disallow non-index Integer types in isassigned (#50594)
Extend #50587 to more general `AbstractArray`s. This is mainly to
disallow `Bool` as an index in `isassigned`, as this isn't supported by
`getindex`. After this
```julia
julia> isassigned(rand(2,2), 1, true)
ERROR: ArgumentError: invalid index: true of type Bool
```
which matches the behavior on v1.9.

(cherry picked from commit b9913973f84b80e9125e37a0312a44bb38239b10)