Fix infinite recursion bug with type mismatch in `unsafe_wrap()`
If a user provides an incorrect pointer type in `unsafe_wrap()`, this
can cause an infinite recursion due to lax type constraints in the last
method of `unsafe_wrap()`.  Example:

```
julia> x = zeros(10)
       unsafe_wrap(Vector{UInt8}, pointer(x), (10*sizeof(eltype(x)),))
ERROR: StackOverflowError:
Stacktrace:
 [1] unsafe_wrap(Atype::Type, p::Ptr{Float64}, dims::Tuple{Int64};
own::Bool) (repeats 19993 times)
   @ Base ./pointer.jl:92
```