Packages incompatible with your Julia version
If a package doesn't have any tagged versions compatible with your julia
version, it complains that

```julia
FixedPoint's requirements can't be satisfied because of the following fixed packages: julia
```
It seems confusing to consider julia a fixed package, so I changed the
message to.
```
ERROR: FixedPoint can't be installed because it has no versions that
support 0.4.0-dev+473 of julia
```

Backport of 5e29071c9582dddf94f6bac3550cfeebc68911a5
ref: #8271