Remove global, globaldecl lowered forms, add Core.globaldecl builtin
We accept `global` in a few more cases where we previously would reject it,
possibly complicating some macros:

julia> global v1

julia> begin
           global v2
           global v3
       end
ERROR: syntax: misplaced "global" declaration
Stacktrace:
 [1] top-level scope
   @ REPL[2]:1

A new ephemeral form in lowering, `unused-only` (analogous to `toplevel-only`),
can be used to mark expressions that should not be assigned to variables, used
as call arguments, etc.  It is more permissive than global's prior behaviour,
failing only when the value is used in non-tail position.