Remove start_repl_server code from REPL module
`REPL.start_repl_server(port::Int)` uses outdated API and no longer functions. It should be removed.

```julia
julia> import REPL

julia> REPL.start_repl_server(8080)
ERROR: MethodError: no method matching listen(::REPL.var"#80#81", ::Int64)
```