Fix #5998
Adds tip from @andrewcooke about deleting Github personal access token
to fix

ERROR: key not found: "token"

error with Pkg.publish()

(cherry picked from commit 51edba97e6af7ee3943cafeb517d5201960c0570)
[av skip]