Fixes error: undefined reference to `JL_PRINTF' see: https://github.com/JuliaLang/julia/issues/10371
Fixes: https://github.com/JuliaLang/julia/issues/10371

seems that some time ago `JL_PRINTF' was removed and `DLLEXPORT int jl_printf(uv_stream_t *s, const char *format, ...);` is used instead

Cheers
P