Fix constructing TCPSocket from RawFD
Without this, an attempt to call this function ends with:

ERROR: LoadError: UndefVarError: pipe not defined
Stacktrace:
 [1] TCPSocket(fd::RawFD)
   @ Sockets /nix/store/w0xq12x4gb3ng0pdh1r9ir4z14pmr3pp-julia-bin-1.7.0/share/julia/stdlib/v1.7/Sockets/src/Sockets.jl:100
 [2] top-level scope

Also add a test for this function. It designed only for Linux, because
I don't know whether it would work on other platforms.