doc: `parentmodule(::Method)`: correct compat note version bound (#60044)
Correct the version bound in the compat note in the doc string: on v1.9
the call immediately results in a `MethodError`:

```
MethodError: no method matching parentmodule(::Method)
```

Doc string (and feature) introduced in PR #47548.