Warn about negative size in array construction (#56262)
After this,
```julia
julia> zeros(-1)
ERROR: ArgumentError: invalid GenericMemory size: the number of elements is either negative or too large for system address width
[...]
```
The error message is updated to warn about possible negative sizes when
creating arrays.

Fixes https://github.com/JuliaLang/julia/issues/55446