InteractiveUtils: escape macro keywords
Previously `@code_typed` and its family can't accept variables as
keyword options since they're not escaped:
```julia
julia> let
           opt = false
           @code_typed optimize=opt sum(1:10)
       end
ERROR: UndefVarError: opt not defined
Stacktrace:
 [1] macro expansion
   @ ~/julia/julia/usr/share/julia/stdlib/v1.7/InteractiveUtils/src/macros.jl:222 [inlined]
 [2] top-level scope
   @ REPL[1]:3
```