Update modules.rst adding type to show for v0.5
Update to add type annotation otherwise we get
```
ERROR: MethodError: no method matching display(::MyType)
```