LLVM now requires `-std=c++14` or higher
Without these compiler flags, we run into errors such as:

```
error: unknown type name 'constexpr'
```

when including `llvm/Support/type_traits.h`