Fix "applicable method may be too new" error on @activate Compiler
Since cd0267113cecb6102d4dd273786f7a8aa790f0d3, @activate Compiler results in a
message like this because it is missing a world age update:
```
ERROR: MethodError: no method matching activate!(; codegen::Bool)
The applicable method may be too new: running in world age 39820, while current world is 39821.

Closest candidates are:
  activate!(; reflection, codegen) (method too new to be called from this world context.)
   @ Compiler ~/julia/Compiler/src/bootstrap.jl:83
```

This change reverts the macro to the old version that `Base.require`s in a
separate toplevel statement.