MersenneTwister: fix constructor involving jumped state
`show` for `MersenneTwister` outputs valid input syntax, by dumping
a condensed state, which can be used to reconstruct the real state.

In the case where an rng is used, then jumped, the output state
was triggering an assertion error when parsed back; this assertion
was wrong, so remove it. For example:
```
julia> m = MersenneTwister(123); rand(m); Random.jump!(m, big(10)^20)
MersenneTwister(0xf80cc98..., 0xea7a7d..., 100000000000000000000, 1002)

julia> MersenneTwister(0xf80cc98..., 0xea7a7d..., 100000000000000000000, 1002)
ERROR: AssertionError: adv == 0
Stacktrace:
[...]
```