fix buffer size bug in Readline.edit_replace
A symptom of this is if

    ext(c)<left><left><left><tab><enter>

is entered into a fresh session, the output is

    extrema (generic function with 2 methods)

instead of the expected

    ERROR: c not defined