libjulia: add jl_unwrap_unionall to exported_funcs (#51916)
This was recently refactored in #51319 and while trying to adapt
`libcxxwrap-julia` to the new changes I got:
```
ld: CMakeFiles/test_module.dir/test_module.cpp.o: in function `jl_datatype_layout':
test_module.cpp:(.text+0x2c2): undefined reference to `jl_unwrap_unionall'
```

The function `jl_datatype_layout` is `STATIC_INLINE` in `julia.h`:

https://github.com/JuliaLang/julia/blob/98542d748540e2390d6222282749c7dd534544da/src/julia.h#L1304-L1312
`jl_unwrap_unionall` is marked `JL_DLLEXPORT` here but it doesn't appear
in the exports of `libjulia`.